import { useRouter } from 'next/router'
import Head from 'next/head'
import StartBtn from '../components/buttons/StartBtn'
import { Container } from '../components/defaults/sharedstyles'
import PokemonLogo from '../components/img/PokemonLogo'

export default function Home() {
  const router = useRouter()

  const goToPlay = () => {
    router.push('/play')
  }

  return (
    <Container>
      <Head>
        <title>Pokemon App</title>
        <meta name="description" content="Generated by Yan Silva" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PokemonLogo />
      <StartBtn onClick={() => goToPlay()}>start</StartBtn>
    </Container>
  )
}
